name: "Gradle Build Action"
description: 'Executes a Gradle build, caching useful state in the GitHub actions cache'

# https://help.github.com/en/articles/metadata-syntax-for-github-actions

inputs:
  gradle-executable:
    description: Path to the Gradle executable
    required: false
  gradle-version:
    description: Gradle version to use
    required: false
  build-root-directory:
    description: Path to the root directory of the build
    required: false
  arguments:
    description: Gradle command line arguments (supports multi-line input)
    required: false
  cache-disabled:
    description: When 'true', all caching is disabled. No entries will be written to or read from the cache.
    required: false
    default: false
  cache-read-only:
    description: When 'true', existing entries will be read from the cache but no entries will be written
    required: false
    # TODO: It might be useful to default to read-only for PRs, or non-main branch.
    default: false 
  
  workflow-job-context:
    description: Used to uniquely identify the current job invocation. Defaults to the matrix values for this job; this should not be overridden by users.
    required: false
    default: ${{ toJSON(matrix) }}
  cache-artifact-bundles:
    description: Names and patterns of artifact bundles to cache separately. For internal use only.
    required: false
    default: |
        [
          ["generated-gradle-jars", "caches/*/generated-gradle-jars/*.jar"],
          ["wrapper-zips", "wrapper/dists/*/*/*.zip"],
          ["dependency-jars", "caches/modules-*/files-*/**/*.jar"],
          ["instrumented-jars", "caches/jars-*/*"]
        ]

outputs:
  build-scan-url:
    description: Link to the build scan if any

runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: success()

branding:
  icon: 'box'
  color: 'gray-dark'
