name: dev

on:
  pull_request:
  push:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build
      run: |
        npm install
        npm run all
    - name: Test wrapper
      uses: ./
      with:
        wrapper-directory: __tests__/data/basic
        build-root-directory: __tests__/data/basic
        arguments: test
    - name: Test dist download
      uses: ./
      with:
        gradle-version: 6.5
        build-root-directory: __tests__/data/basic
        arguments: test
