name: dev

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
    - uses: ./
      with:
        wrapper-directory: __tests__/data/basic
        build-root-directory: __tests__/data/basic
        arguments: help
