name: Execute failure cases

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  CACHE_KEY_PREFIX: ${{github.workflow}}#${{github.run_number}}-

jobs:

  wrapper-missing:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Test wrapper missing
      uses: ./
      with:
        build-root-directory: __tests__/samples/no-wrapper
        arguments: help

  bad-configuration:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Test bad config value
      uses: ./
      with:
        build-root-directory: __tests__/samples/no-wrapper
        arguments: help
        cache-disabled: yes
