name: Test different action inputs

on:
  workflow_call:
    inputs:
      cache-key-prefix:
        type: string
  workflow_dispatch:

env:
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: action-inputs-${{ inputs.cache-key-prefix }}
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  action-inputs:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Invoke with multi-line arguments
      uses: ./
      with:
        build-root-directory: .github/workflow-samples/groovy-dsl
        arguments: |
            --configuration-cache
            --build-cache
            -DsystemProperty=FOO
            -PgradleProperty=BAR
            test
            jar