name: Test caching

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  CACHE_KEY_PREFIX: ${{github.workflow}}#${{github.run_number}}-

jobs:
  # Run initial Gradle builds to push initial cache entries
  # These builds should start fresh without cache hits, due to the seed injected into the cache key above.
  seed-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build using Gradle wrapper
      uses: ./
      with:
        build-root-directory: __tests__/samples/basic
        arguments: test
    - name: Build with configuration-cache enabled
      uses: ./
      with:
        build-root-directory: __tests__/samples/basic
        arguments: test --configuration-cache

  # Test that the gradle-user-home cache will cache dependencies, by running build with --offline
  dependencies-cache:
    needs: seed-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Execute Gradle build with --offline
      uses: ./
      with:
        build-root-directory: __tests__/samples/basic
        arguments: test --offline
        cache-read-only: true

  # Test that the gradle-user-home cache will cache and restore local build-cache
  build-cache:
    needs: seed-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Execute Gradle build and verify tasks from cache
      uses: ./
      with:
        build-root-directory: __tests__/samples/basic
        arguments: test -DverifyCachedBuild=true
        cache-read-only: true

  # Test that the project-dot-gradle cache will cache and restore configuration-cache
  configuration-cache:
    needs: seed-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Execute Gradle build and verify cached configuration
      uses: ./
      env: 
        VERIFY_CACHED_CONFIGURATION: true
      with:
        build-root-directory: __tests__/samples/basic
        arguments: test --configuration-cache
        cache-read-only: true
