name: Test save/restore Gradle Home with direct execution

on:
  workflow_call:
    inputs:
      cache-key-prefix:
        type: string
  workflow_dispatch:

env:
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: execution-with-caching-${{ inputs.cache-key-prefix }}
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Execute Gradle build
      uses: ./
      with:
        build-root-directory: .github/workflow-samples/groovy-dsl
        arguments: test

  # Test that the gradle-user-home is restored
  verify-build:
    needs: seed-build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Execute Gradle build
      uses: ./
      with:
        cache-read-only: true
        build-root-directory: .github/workflow-samples/groovy-dsl
        arguments: test --offline -DverifyCachedBuild=true

