 # make sure the action works on a clean machine without building
name: prod

on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Test wrapper
      uses: ./
      with:
        wrapper-directory: __tests__/data/basic
        build-root-directory: __tests__/data/basic
        arguments: help
    - name: Test dist download
      uses: ./
      with:
        gradle-version: 6.5
        build-root-directory: __tests__/data/basic
        arguments: help
    - name: Check for uncommitted changes
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run all'" \
                 "and check in all changes" \
            && exit 1)
